version: '3'
services:
  app:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://username:password@postgres:5432/mydatabase
    command: sh -c "npm install -g pnpm && apt update && apt-get install -y chromium && pnpm install && pnpx prisma generate && pnpm run start:dev"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
